project:
  type: website
  output-dir: docs

website:
  title: "Bruon"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - searches.qmd

format:
  html:
    theme: cosmo
    lang: pt
    css: styles.css
    toc: true



