project:
  type: website
  output-dir: docs

website:
  title: "Bruon"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: sobre.qmd
        text: Sobre
      - href: pesquisas.qmd
        text: Pesquisas
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    lang: pt
    css: styles.css
    toc: true



